services:
  - type: web
    name: pitchdeck-classifier
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: APP_PASSWORD
        sync: false
